[project]
name = "PACK NAME"
version = "PACK VERSION"
packages-dir = "packages"
src-dir = "src"

# Optional
# [[project.authors]]
# name = "PACK AUTHOR"
# email = "PACK AUTHOR'S EMAIL"

# Optional
# [project.urls]
# Author = "PACK AUTHOR URL"
# Repository = "PACK REPOSITORY URL"
# Modrinth = " PACK MODRINTH URL"
# CurseForge = "PACK CURSEFORGE URL"

# Keep this
[[tool.mc-pack-env.authors]]
name = "SegaBASS (segabass65)"
email = "segabass65@proton.me"

# Optional
[tool.mc-pack-env.urls]
Author = "https://github.com/segabass65"
Repository = "https://github.com/segabass65/mc-pack-env"
